import { ListingForm, TestimonialForm } from "@/types/dashboard";

export const initialListings: ListingForm[] = [
  {
    id: 1,
    name: "Costa Peruana 2182 | Playa Señoritas",
    location: "Playa Señoritas · Punta Hermosa",
    price: "Desde S/. 850",
    slug: "beachfront-playa-senoritas-piscina-terraza",
    guests: 6,
    bedrooms: 2,
    bathrooms: 2,
    airbnbUrl: "https://airbnb.com",
    featured: true,
    amenities: [
      { id: "1", icon: "beach", label: "Frente a la playa" },
      { id: "2", icon: "ac", label: "Aire Acondicionado" },
      { id: "3", icon: "grill", label: "Parrilla" },
      { id: "4", icon: "terrace", label: "Terraza" },
      { id: "5", icon: "security", label: "Seguridad garantizada" },
      { id: "6", icon: "kitchen", label: "Cocina Equipada" },
      { id: "7", icon: "pool", label: "Piscina Temperada" },
      { id: "8", icon: "wifi", label: "Zona de trabajo" },
      { id: "9", icon: "coffee", label: "Cafetera" },
      { id: "10", icon: "bedding", label: "Ropa de Cama" },
      { id: "11", icon: "bath", label: "Artículos de Aseo" },
      { id: "12", icon: "parking", label: "Estacionamiento" },
    ],
    images: [],
  },
  {
    id: 2,
    name: "Blue Paradise XIII | Playa Caballeros",
    location: "Playa Caballeros · Punta Hermosa",
    price: "Desde S/. 850",
    slug: "paradise-in-stunning-beach-house-playa-caballeros",
    guests: 8,
    bedrooms: 3,
    bathrooms: 2,
    airbnbUrl: "https://airbnb.com",
    featured: false,
    amenities: [
      { id: "1", icon: "beach", label: "Frente a la playa" },
      { id: "2", icon: "grill", label: "Parrilla" },
      { id: "3", icon: "terrace", label: "Terraza amplia" },
      { id: "4", icon: "security", label: "Seguridad garantizada" },
      { id: "5", icon: "kitchen", label: "Cocina Equipada" },
      { id: "6", icon: "pool", label: "Piscina grande" },
      { id: "7", icon: "wifi", label: "Zona de trabajo" },
      { id: "8", icon: "coffee", label: "Cafetera" },
      { id: "9", icon: "bedding", label: "Ropa de Cama" },
      { id: "10", icon: "bath", label: "Artículos de Aseo" },
      { id: "11", icon: "parking", label: "Estacionamiento" },
      { id: "12", icon: "gym", label: "Gimnasio" },
    ],
    images: [],
  },
  {
    id: 3,
    name: "Mirador del Mar | Dúplex con piscina",
    location: "Mirador del Mar · Punta Hermosa",
    price: "Consultar",
    slug: "duplex-mirador-del-mar-pool-best-view",
    guests: 10,
    bedrooms: 4,
    bathrooms: 3,
    airbnbUrl: "https://airbnb.com",
    featured: false,
    amenities: [
      { id: "1", icon: "beach", label: "Vista al mar" },
      { id: "2", icon: "ac", label: "Aire acondicionado" },
      { id: "3", icon: "grill", label: "Parrilla" },
      { id: "4", icon: "terrace", label: "Terraza amplia" },
      { id: "5", icon: "security", label: "Seguridad" },
      { id: "6", icon: "kitchen", label: "Cocina equipada" },
      { id: "7", icon: "pool", label: "Piscina" },
      { id: "8", icon: "wifi", label: "WiFi" },
      { id: "9", icon: "coffee", label: "Cafetera" },
      { id: "10", icon: "bedding", label: "Ropa de cama" },
      { id: "11", icon: "bath", label: "Baños completos" },
      { id: "12", icon: "parking", label: "2 Estacionamientos" },
      { id: "13", icon: "gym", label: "Gimnasio" },
    ],
    images: [],
  },
  {
    id: 4,
    name: "Sunset View Dúplex",
    location: "Sunset View · Punta Hermosa",
    price: "Consultar",
    slug: "sunset-view-duplex",
    guests: 8,
    bedrooms: 3,
    bathrooms: 2,
    airbnbUrl: "https://airbnb.com",
    featured: false,
    amenities: [
      { id: "1", icon: "beach", label: "Cerca al mar" },
      { id: "2", icon: "terrace", label: "Terraza" },
      { id: "3", icon: "pool", label: "Piscina" },
      { id: "4", icon: "kitchen", label: "Cocina equipada" },
      { id: "5", icon: "wifi", label: "WiFi" },
      { id: "6", icon: "parking", label: "Estacionamiento" },
    ],
    images: [],
  },
  {
    id: 5,
    name: "Vista Mar Prime",
    location: "Vista Mar Prime · Punta Hermosa",
    price: "Consultar",
    slug: "vista-mar-prime",
    guests: 12,
    bedrooms: 5,
    bathrooms: 4,
    airbnbUrl: "https://airbnb.com",
    featured: false,
    amenities: [
      { id: "1", icon: "beach", label: "Vista a la playa" },
      { id: "2", icon: "ac", label: "Aire acondicionado" },
      { id: "3", icon: "grill", label: "Parrilla" },
      { id: "4", icon: "pool", label: "Piscina" },
      { id: "5", icon: "kitchen", label: "Cocina equipada" },
      { id: "6", icon: "wifi", label: "WiFi" },
      { id: "7", icon: "parking", label: "Estacionamientos" },
    ],
    images: [],
  },
];

export const initialTestimonials: TestimonialForm[] = [
  {
    id: 1,
    name: "Tatiana",
    text: "Un apartamento precioso, vista al mar y limpieza impecable.",
    type: "Familia",
  },
  {
    id: 2,
    name: "David Bermúdez",
    text: "Todo perfecto desde el check-in. William atento siempre.",
    type: "Amigos",
  },
  {
    id: 3,
    name: "Raquel",
    text: "Espacioso, limpio y seguro. Vista hermosa y cerca de restaurantes.",
    type: "Estadia",
  },
];
